apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-agg
  namespace: dynamo-system
spec:
  services:
    Frontend:
      envFromSecret: hf-token-secret
      componentType: frontend
      replicas: 1
      extraPodSpec:
        # optional: keep frontend off GPU node by omitting nodeSelector
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.1.0

    VllmDecodeWorker:
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      resources:
        limits:
          gpu: "1"
        requests:
          custom:
            # Increase this value for larger models.
            ephemeral-storage: "2Gi"
      extraPodSpec:
        runtimeClassName: nvidia
        nodeSelector:
          ucloud.dk/gpu: "true"
        # optional: add tolerations if your GPU node ever gets tainted
        # tolerations:
        # - key: "nvidia.com/gpu"
        #   operator: "Exists"
        #   effect: "NoSchedule"
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.1.0
          workingDir: /workspace/examples/backends/vllm
          command: ["python3","-m","dynamo.vllm"]
          args: ["--model","Qwen/Qwen3-0.6B"]
